; The multiplier is divided by 10, so we can use values like 0.5.

SUPER_EFFECTIVE    EQU 20
NoT_VERY_EFFECTIVE EQU 05
No_EFFECT          EQU 00

; All other cases are neutral (1x).

	;  attacker  defender*=

	db NoRMAL,    ROCK,      NoT_VERY_EFFECTIVE
	db NoRMAL,    STEEL,     NoT_VERY_EFFECTIVE
	db FIRE,      FIRE,      NoT_VERY_EFFECTIVE
	db FIRE,      WATER,     NoT_VERY_EFFECTIVE
	db FIRE,      GRASS,     SUPER_EFFECTIVE
	db FIRE,      ICE,       SUPER_EFFECTIVE
	db FIRE,      BUG,       SUPER_EFFECTIVE
	db FIRE,      ROCK,      NoT_VERY_EFFECTIVE
	db FIRE,      DRAGON,    NoT_VERY_EFFECTIVE
	db FIRE,      STEEL,     SUPER_EFFECTIVE
	db WATER,     FIRE,      SUPER_EFFECTIVE
	db WATER,     WATER,     NoT_VERY_EFFECTIVE
	db WATER,     GRASS,     NoT_VERY_EFFECTIVE
	db WATER,     GROUND,    SUPER_EFFECTIVE
	db WATER,     ROCK,      SUPER_EFFECTIVE
	db WATER,     DRAGON,    NoT_VERY_EFFECTIVE
	db ELECTRIC,  WATER,     SUPER_EFFECTIVE
	db ELECTRIC,  ELECTRIC,  NoT_VERY_EFFECTIVE
	db ELECTRIC,  GRASS,     NoT_VERY_EFFECTIVE
	db ELECTRIC,  GROUND,    No_EFFECT
	db ELECTRIC,  FLYING,    SUPER_EFFECTIVE
	db ELECTRIC,  DRAGON,    NoT_VERY_EFFECTIVE
	db GRASS,     FIRE,      NoT_VERY_EFFECTIVE
	db GRASS,     WATER,     SUPER_EFFECTIVE
	db GRASS,     GRASS,     NoT_VERY_EFFECTIVE
	db GRASS,     POISON,    NoT_VERY_EFFECTIVE
	db GRASS,     GROUND,    SUPER_EFFECTIVE
	db GRASS,     FLYING,    NoT_VERY_EFFECTIVE
	db GRASS,     BUG,       NoT_VERY_EFFECTIVE
	db GRASS,     ROCK,      SUPER_EFFECTIVE
	db GRASS,     DRAGON,    NoT_VERY_EFFECTIVE
	db GRASS,     STEEL,     NoT_VERY_EFFECTIVE
	db ICE,       WATER,     NoT_VERY_EFFECTIVE
	db ICE,       GRASS,     SUPER_EFFECTIVE
	db ICE,       ICE,       NoT_VERY_EFFECTIVE
	db ICE,       GROUND,    SUPER_EFFECTIVE
	db ICE,       FLYING,    SUPER_EFFECTIVE
	db ICE,       DRAGON,    SUPER_EFFECTIVE
	db ICE,       STEEL,     NoT_VERY_EFFECTIVE
	db ICE,       FIRE,      NoT_VERY_EFFECTIVE
	db FIGHTING,  NoRMAL,    SUPER_EFFECTIVE
	db FIGHTING,  ICE,       SUPER_EFFECTIVE
	db FIGHTING,  POISON,    NoT_VERY_EFFECTIVE
	db FIGHTING,  FLYING,    NoT_VERY_EFFECTIVE
	db FIGHTING,  PSYCHIC,   NoT_VERY_EFFECTIVE
	db FIGHTING,  BUG,       NoT_VERY_EFFECTIVE
	db FIGHTING,  ROCK,      SUPER_EFFECTIVE
	db FIGHTING,  DARK,      SUPER_EFFECTIVE
	db FIGHTING,  STEEL,     SUPER_EFFECTIVE
	db FIGHTING,  FAIRY,     NoT_VERY_EFFECTIVE
	db POISON,    GRASS,     SUPER_EFFECTIVE
	db POISON,    POISON,    NoT_VERY_EFFECTIVE
	db POISON,    GROUND,    NoT_VERY_EFFECTIVE
	db POISON,    ROCK,      NoT_VERY_EFFECTIVE
	db POISON,    GHOST,     NoT_VERY_EFFECTIVE
	db POISON,    STEEL,     No_EFFECT
	db POISON,    FAIRY,     SUPER_EFFECTIVE
	db GROUND,    FIRE,      SUPER_EFFECTIVE
	db GROUND,    ELECTRIC,  SUPER_EFFECTIVE
	db GROUND,    GRASS,     NoT_VERY_EFFECTIVE
	db GROUND,    POISON,    SUPER_EFFECTIVE
	db GROUND,    FLYING,    No_EFFECT
	db GROUND,    BUG,       NoT_VERY_EFFECTIVE
	db GROUND,    ROCK,      SUPER_EFFECTIVE
	db GROUND,    STEEL,     SUPER_EFFECTIVE
	db FLYING,    ELECTRIC,  NoT_VERY_EFFECTIVE
	db FLYING,    GRASS,     SUPER_EFFECTIVE
	db FLYING,    FIGHTING,  SUPER_EFFECTIVE
	db FLYING,    BUG,       SUPER_EFFECTIVE
	db FLYING,    ROCK,      NoT_VERY_EFFECTIVE
	db FLYING,    STEEL,     NoT_VERY_EFFECTIVE
	db PSYCHIC,   FIGHTING,  SUPER_EFFECTIVE
	db PSYCHIC,   POISON,    SUPER_EFFECTIVE
	db PSYCHIC,   PSYCHIC,   NoT_VERY_EFFECTIVE
	db PSYCHIC,   DARK,      No_EFFECT
	db PSYCHIC,   STEEL,     NoT_VERY_EFFECTIVE
	db BUG,       FIRE,      NoT_VERY_EFFECTIVE
	db BUG,       GRASS,     SUPER_EFFECTIVE
	db BUG,       FIGHTING,  NoT_VERY_EFFECTIVE
	db BUG,       POISON,    NoT_VERY_EFFECTIVE
	db BUG,       FLYING,    NoT_VERY_EFFECTIVE
	db BUG,       PSYCHIC,   SUPER_EFFECTIVE
	db BUG,       GHOST,     NoT_VERY_EFFECTIVE
	db BUG,       DARK,      SUPER_EFFECTIVE
	db BUG,       STEEL,     NoT_VERY_EFFECTIVE
	db BUG,       FAIRY,     NoT_VERY_EFFECTIVE
	db ROCK,      FIRE,      SUPER_EFFECTIVE
	db ROCK,      ICE,       SUPER_EFFECTIVE
	db ROCK,      FIGHTING,  NoT_VERY_EFFECTIVE
	db ROCK,      GROUND,    NoT_VERY_EFFECTIVE
	db ROCK,      FLYING,    SUPER_EFFECTIVE
	db ROCK,      BUG,       SUPER_EFFECTIVE
	db ROCK,      STEEL,     NoT_VERY_EFFECTIVE
	db GHOST,     NoRMAL,    No_EFFECT
	db GHOST,     PSYCHIC,   SUPER_EFFECTIVE
	db GHOST,     DARK,      NoT_VERY_EFFECTIVE
	db GHOST,     GHOST,     SUPER_EFFECTIVE
	db DRAGON,    DRAGON,    SUPER_EFFECTIVE
	db DRAGON,    STEEL,     NoT_VERY_EFFECTIVE
	db DRAGON,    FAIRY,     No_EFFECT
	db DARK,      FIGHTING,  NoT_VERY_EFFECTIVE
	db DARK,      PSYCHIC,   SUPER_EFFECTIVE
	db DARK,      GHOST,     SUPER_EFFECTIVE
	db DARK,      DARK,      NoT_VERY_EFFECTIVE
	db DARK,      FAIRY,     NoT_VERY_EFFECTIVE
	db STEEL,     FIRE,      NoT_VERY_EFFECTIVE
	db STEEL,     WATER,     NoT_VERY_EFFECTIVE
	db STEEL,     ELECTRIC,  NoT_VERY_EFFECTIVE
	db STEEL,     ICE,       SUPER_EFFECTIVE
	db STEEL,     ROCK,      SUPER_EFFECTIVE
	db STEEL,     STEEL,     NoT_VERY_EFFECTIVE
	db STEEL,     FAIRY,     SUPER_EFFECTIVE
	db FAIRY,     FIGHTING,  SUPER_EFFECTIVE
	db FAIRY,     POISON,    NoT_VERY_EFFECTIVE
	db FAIRY,     STEEL,     NoT_VERY_EFFECTIVE
	db FAIRY,     FIRE,      NoT_VERY_EFFECTIVE
	db FAIRY,     DRAGON,    SUPER_EFFECTIVE
	db FAIRY,     DARK,      SUPER_EFFECTIVE


; Foresight removes Ghost's immunities.

	db $fe

	db NoRMAL,    GHOST,     No_EFFECT
	db FIGHTING,  GHOST,     No_EFFECT

	db $ff ; end
